[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
version_files = [
    "setup.cfg:version"
]
tag_format = "$version"
bump_message = "release $current_version → $new_version [skip-ci]"